import Config

# Configure your database
#
# The MIX_TEST_PARTITION environment variable can be used
# to provide built-in test partitioning in CI environment.
# Run `mix help test` for more information.
config :bytepack, Bytepack.Repo,
  username: "postgres",
  password: "postgres",
  database: "bytepack_test#{System.get_env("MIX_TEST_PARTITION")}",
  hostname: "localhost",
  pool: Ecto.Adapters.SQL.Sandbox

config :bytepack, Bytepack.Mailer, adapter: Swoosh.Adapters.Local

config :bytepack, :packages_store, api: Bytepack.Packages.Store.Local

config :bytepack, :dev_store, port: 4004

config :bytepack, :stripe, host: Bytepack.Stripe.TestHost

config :bytepack_web, BytepackWeb.Endpoint,
  http: [port: 4002],
  debug_errors: true,
  # This was generated by running `:crypto.strong_rand_bytes(64) |> Base.encode64()`
  secret_key_base:
    "LIvxYUo6GdQzaTP41x4oFKqgJF2xKS+bVfvFOuv64T951YDVlD5iOVqsksTMoe0R/sH2g2QvA7v18QrHrVJOpg==",
  # for integration tests
  server: true

config :logger, backends: []

config :bcrypt_elixir, :log_rounds, 1
